@startuml

left to right direction
node Agent as "Agent space" #palegreen {
	actor Agent.agent as "Agent"

	rectangle Accounts {
		collections Account.credits as "Credits (₡)"
		storage Agent.UBI as "UBI"
	}
}

interface Vote as "vote"

database AgentParams as "Agent params" {
	storage AgentParams.UBI as "UBI amount"
}

database EconParams as "Economic params" {
	storage EconParams.Occ as "Occupations"
	storage EconParams.Trk as "Trackers"
	storage EconParams.Proc as "Processes"
}

component Cost as "Cost<>" {
}

node Bloc {
	rectangle Bloc.cost as "Costs" {
		component Resource.cost as "Cost<Resource>"
		component Process.cost as "Cost<Process>"
		storage Bloc.Allowance as "Cost allowance"
	}
	node Resource
	interface Price
}

rectangle Investment {
	hexagon Cyber as "Cybernetics"
	interface Invest
}

rectangle EcActions as "Economic actions" {
	interface Order as "order"
	interface Work as "work"
	interface Use as "use"
	interface Consume as "consume"
	interface Transfer as "transfer"
}

Agent.agent -l-> Vote
Agent.agent -d-> Consume
Agent.agent -d-> Use
Agent.agent -d-> Work
Agent.agent -[#blue,thickness=2]* Bloc : "Membership"
Agent.agent -u-> Invest
Accounts .> Use
Accounts .> Consume
Vote -d-> AgentParams
Vote -d--> EconParams
Bloc <-> Order
Bloc -> Transfer
Bloc.cost .[thickness=2]> Price
Bloc.cost .[thickness=4].> Cyber
AgentParams.UBI .> Agent.UBI
EconParams.Occ .d.> Cost
EconParams.Trk .d.> Cost
EconParams.Proc .d.> Cost
Price -> Consume
Price .> Cyber
Investment .[thickness=4].> Bloc.Allowance
Work .> Account.credits
Transfer -d-> Bloc
Resource -u-> Consume
Resource -u-> Use
Resource -u-> Transfer
EcActions .[thickness=4]> Cyber
EcActions .[thickness=4].> Bloc.cost

@enduml

